// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.11.2
// source: irrigation.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Solenoid_State int32

const (
	Solenoid_OFF Solenoid_State = 0
	Solenoid_ON  Solenoid_State = 1
)

// Enum value maps for Solenoid_State.
var (
	Solenoid_State_name = map[int32]string{
		0: "OFF",
		1: "ON",
	}
	Solenoid_State_value = map[string]int32{
		"OFF": 0,
		"ON":  1,
	}
)

func (x Solenoid_State) Enum() *Solenoid_State {
	p := new(Solenoid_State)
	*p = x
	return p
}

func (x Solenoid_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Solenoid_State) Descriptor() protoreflect.EnumDescriptor {
	return file_irrigation_proto_enumTypes[0].Descriptor()
}

func (Solenoid_State) Type() protoreflect.EnumType {
	return &file_irrigation_proto_enumTypes[0]
}

func (x Solenoid_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Solenoid_State.Descriptor instead.
func (Solenoid_State) EnumDescriptor() ([]byte, []int) {
	return file_irrigation_proto_rawDescGZIP(), []int{0, 0}
}

type Solenoid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State              Solenoid_State `protobuf:"varint,1,opt,name=state,proto3,enum=Solenoid_State" json:"state,omitempty"`
	Pin                int32          `protobuf:"varint,2,opt,name=pin,proto3" json:"pin,omitempty"`
	Override           bool           `protobuf:"varint,3,opt,name=override,proto3" json:"override,omitempty"`
	LitresToDispense   int32          `protobuf:"varint,4,opt,name=litresToDispense,proto3" json:"litresToDispense,omitempty"`
	LengthOfSoakerHose float32        `protobuf:"fixed32,5,opt,name=lengthOfSoakerHose,proto3" json:"lengthOfSoakerHose,omitempty"`
	LitresDispensed    float32        `protobuf:"fixed32,6,opt,name=litresDispensed,proto3" json:"litresDispensed,omitempty"`
	LastOverridden     int32          `protobuf:"varint,7,opt,name=lastOverridden,proto3" json:"lastOverridden,omitempty"`
}

func (x *Solenoid) Reset() {
	*x = Solenoid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_irrigation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Solenoid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Solenoid) ProtoMessage() {}

func (x *Solenoid) ProtoReflect() protoreflect.Message {
	mi := &file_irrigation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Solenoid.ProtoReflect.Descriptor instead.
func (*Solenoid) Descriptor() ([]byte, []int) {
	return file_irrigation_proto_rawDescGZIP(), []int{0}
}

func (x *Solenoid) GetState() Solenoid_State {
	if x != nil {
		return x.State
	}
	return Solenoid_OFF
}

func (x *Solenoid) GetPin() int32 {
	if x != nil {
		return x.Pin
	}
	return 0
}

func (x *Solenoid) GetOverride() bool {
	if x != nil {
		return x.Override
	}
	return false
}

func (x *Solenoid) GetLitresToDispense() int32 {
	if x != nil {
		return x.LitresToDispense
	}
	return 0
}

func (x *Solenoid) GetLengthOfSoakerHose() float32 {
	if x != nil {
		return x.LengthOfSoakerHose
	}
	return 0
}

func (x *Solenoid) GetLitresDispensed() float32 {
	if x != nil {
		return x.LitresDispensed
	}
	return 0
}

func (x *Solenoid) GetLastOverridden() int32 {
	if x != nil {
		return x.LastOverridden
	}
	return 0
}

type Irrigator struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int32       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Solenoids   []*Solenoid `protobuf:"bytes,2,rep,name=solenoids,proto3" json:"solenoids,omitempty"`
	LastWatered int64       `protobuf:"varint,3,opt,name=lastWatered,proto3" json:"lastWatered,omitempty"`
	Timestamp   int64       `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	RainLockout bool        `protobuf:"varint,5,opt,name=rainLockout,proto3" json:"rainLockout,omitempty"`
	LastLockout int64       `protobuf:"varint,6,opt,name=lastLockout,proto3" json:"lastLockout,omitempty"`
	Irrigating  bool        `protobuf:"varint,7,opt,name=irrigating,proto3" json:"irrigating,omitempty"`
	Temperature float32     `protobuf:"fixed32,8,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Timing      int64       `protobuf:"varint,9,opt,name=timing,proto3" json:"timing,omitempty"`
}

func (x *Irrigator) Reset() {
	*x = Irrigator{}
	if protoimpl.UnsafeEnabled {
		mi := &file_irrigation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Irrigator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Irrigator) ProtoMessage() {}

func (x *Irrigator) ProtoReflect() protoreflect.Message {
	mi := &file_irrigation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Irrigator.ProtoReflect.Descriptor instead.
func (*Irrigator) Descriptor() ([]byte, []int) {
	return file_irrigation_proto_rawDescGZIP(), []int{1}
}

func (x *Irrigator) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Irrigator) GetSolenoids() []*Solenoid {
	if x != nil {
		return x.Solenoids
	}
	return nil
}

func (x *Irrigator) GetLastWatered() int64 {
	if x != nil {
		return x.LastWatered
	}
	return 0
}

func (x *Irrigator) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Irrigator) GetRainLockout() bool {
	if x != nil {
		return x.RainLockout
	}
	return false
}

func (x *Irrigator) GetLastLockout() int64 {
	if x != nil {
		return x.LastLockout
	}
	return 0
}

func (x *Irrigator) GetIrrigating() bool {
	if x != nil {
		return x.Irrigating
	}
	return false
}

func (x *Irrigator) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *Irrigator) GetTiming() int64 {
	if x != nil {
		return x.Timing
	}
	return 0
}

type IrrigationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *IrrigationRequest) Reset() {
	*x = IrrigationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_irrigation_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IrrigationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IrrigationRequest) ProtoMessage() {}

func (x *IrrigationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_irrigation_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IrrigationRequest.ProtoReflect.Descriptor instead.
func (*IrrigationRequest) Descriptor() ([]byte, []int) {
	return file_irrigation_proto_rawDescGZIP(), []int{2}
}

func (x *IrrigationRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type EmptyMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyMessage) Reset() {
	*x = EmptyMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_irrigation_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyMessage) ProtoMessage() {}

func (x *EmptyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_irrigation_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyMessage.ProtoReflect.Descriptor instead.
func (*EmptyMessage) Descriptor() ([]byte, []int) {
	return file_irrigation_proto_rawDescGZIP(), []int{3}
}

var File_irrigation_proto protoreflect.FileDescriptor

var file_irrigation_proto_rawDesc = []byte{
	0x0a, 0x10, 0x69, 0x72, 0x72, 0x69, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xa7, 0x02, 0x0a, 0x08, 0x53, 0x6f, 0x6c, 0x65, 0x6e, 0x6f, 0x69, 0x64, 0x12,
	0x25, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f,
	0x2e, 0x53, 0x6f, 0x6c, 0x65, 0x6e, 0x6f, 0x69, 0x64, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x76, 0x65, 0x72,
	0x72, 0x69, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x6f, 0x76, 0x65, 0x72,
	0x72, 0x69, 0x64, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x6c, 0x69, 0x74, 0x72, 0x65, 0x73, 0x54, 0x6f,
	0x44, 0x69, 0x73, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10,
	0x6c, 0x69, 0x74, 0x72, 0x65, 0x73, 0x54, 0x6f, 0x44, 0x69, 0x73, 0x70, 0x65, 0x6e, 0x73, 0x65,
	0x12, 0x2e, 0x0a, 0x12, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x4f, 0x66, 0x53, 0x6f, 0x61, 0x6b,
	0x65, 0x72, 0x48, 0x6f, 0x73, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x12, 0x6c, 0x65,
	0x6e, 0x67, 0x74, 0x68, 0x4f, 0x66, 0x53, 0x6f, 0x61, 0x6b, 0x65, 0x72, 0x48, 0x6f, 0x73, 0x65,
	0x12, 0x28, 0x0a, 0x0f, 0x6c, 0x69, 0x74, 0x72, 0x65, 0x73, 0x44, 0x69, 0x73, 0x70, 0x65, 0x6e,
	0x73, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0f, 0x6c, 0x69, 0x74, 0x72, 0x65,
	0x73, 0x44, 0x69, 0x73, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x6c, 0x61,
	0x73, 0x74, 0x4f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0e, 0x6c, 0x61, 0x73, 0x74, 0x4f, 0x76, 0x65, 0x72, 0x72, 0x69, 0x64, 0x64,
	0x65, 0x6e, 0x22, 0x18, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x4f,
	0x46, 0x46, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4e, 0x10, 0x01, 0x22, 0xa2, 0x02, 0x0a,
	0x09, 0x49, 0x72, 0x72, 0x69, 0x67, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x27, 0x0a, 0x09, 0x73, 0x6f,
	0x6c, 0x65, 0x6e, 0x6f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e,
	0x53, 0x6f, 0x6c, 0x65, 0x6e, 0x6f, 0x69, 0x64, 0x52, 0x09, 0x73, 0x6f, 0x6c, 0x65, 0x6e, 0x6f,
	0x69, 0x64, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x57, 0x61, 0x74, 0x65, 0x72,
	0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x57, 0x61,
	0x74, 0x65, 0x72, 0x65, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x61, 0x69, 0x6e, 0x4c, 0x6f, 0x63, 0x6b, 0x6f,
	0x75, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x72, 0x61, 0x69, 0x6e, 0x4c, 0x6f,
	0x63, 0x6b, 0x6f, 0x75, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x4c, 0x6f, 0x63,
	0x6b, 0x6f, 0x75, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x6c, 0x61, 0x73, 0x74,
	0x4c, 0x6f, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x72, 0x72, 0x69, 0x67,
	0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x72, 0x72,
	0x69, 0x67, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x74, 0x65,
	0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x69, 0x6d,
	0x69, 0x6e, 0x67, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x74, 0x69, 0x6d, 0x69, 0x6e,
	0x67, 0x22, 0x23, 0x0a, 0x11, 0x49, 0x72, 0x72, 0x69, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x0e, 0x0a, 0x0c, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x60, 0x0a, 0x0a, 0x49, 0x72, 0x72, 0x69, 0x67, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x12, 0x12, 0x2e, 0x49, 0x72, 0x72, 0x69, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x0a, 0x2e, 0x49, 0x72, 0x72, 0x69, 0x67, 0x61, 0x74, 0x6f, 0x72,
	0x22, 0x00, 0x12, 0x24, 0x0a, 0x08, 0x53, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0a,
	0x2e, 0x49, 0x72, 0x72, 0x69, 0x67, 0x61, 0x74, 0x6f, 0x72, 0x1a, 0x0a, 0x2e, 0x49, 0x72, 0x72,
	0x69, 0x67, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x00, 0x42, 0x1b, 0x5a, 0x19, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x65, 0x68, 0x61, 0x61, 0x73, 0x73, 0x2f, 0x63,
	0x6d, 0x64, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_irrigation_proto_rawDescOnce sync.Once
	file_irrigation_proto_rawDescData = file_irrigation_proto_rawDesc
)

func file_irrigation_proto_rawDescGZIP() []byte {
	file_irrigation_proto_rawDescOnce.Do(func() {
		file_irrigation_proto_rawDescData = protoimpl.X.CompressGZIP(file_irrigation_proto_rawDescData)
	})
	return file_irrigation_proto_rawDescData
}

var file_irrigation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_irrigation_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_irrigation_proto_goTypes = []interface{}{
	(Solenoid_State)(0),       // 0: Solenoid.State
	(*Solenoid)(nil),          // 1: Solenoid
	(*Irrigator)(nil),         // 2: Irrigator
	(*IrrigationRequest)(nil), // 3: IrrigationRequest
	(*EmptyMessage)(nil),      // 4: EmptyMessage
}
var file_irrigation_proto_depIdxs = []int32{
	0, // 0: Solenoid.state:type_name -> Solenoid.State
	1, // 1: Irrigator.solenoids:type_name -> Solenoid
	3, // 2: Irrigation.GetState:input_type -> IrrigationRequest
	2, // 3: Irrigation.SetState:input_type -> Irrigator
	2, // 4: Irrigation.GetState:output_type -> Irrigator
	2, // 5: Irrigation.SetState:output_type -> Irrigator
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_irrigation_proto_init() }
func file_irrigation_proto_init() {
	if File_irrigation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_irrigation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Solenoid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_irrigation_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Irrigator); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_irrigation_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IrrigationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_irrigation_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_irrigation_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_irrigation_proto_goTypes,
		DependencyIndexes: file_irrigation_proto_depIdxs,
		EnumInfos:         file_irrigation_proto_enumTypes,
		MessageInfos:      file_irrigation_proto_msgTypes,
	}.Build()
	File_irrigation_proto = out.File
	file_irrigation_proto_rawDesc = nil
	file_irrigation_proto_goTypes = nil
	file_irrigation_proto_depIdxs = nil
}
