// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.1
// source: lighting.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Type int32

const (
	Type_RGB  Type = 0
	Type_RGBW Type = 1
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "RGB",
		1: "RGBW",
	}
	Type_value = map[string]int32{
		"RGB":  0,
		"RGBW": 1,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_lighting_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_lighting_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_lighting_proto_rawDescGZIP(), []int{0}
}

type Light struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Powered bool   `protobuf:"varint,1,opt,name=powered,proto3" json:"powered,omitempty"`
	Type    Type   `protobuf:"varint,2,opt,name=type,proto3,enum=Type" json:"type,omitempty"`
	Color   uint32 `protobuf:"varint,3,opt,name=color,proto3" json:"color,omitempty"`
}

func (x *Light) Reset() {
	*x = Light{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lighting_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Light) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Light) ProtoMessage() {}

func (x *Light) ProtoReflect() protoreflect.Message {
	mi := &file_lighting_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Light.ProtoReflect.Descriptor instead.
func (*Light) Descriptor() ([]byte, []int) {
	return file_lighting_proto_rawDescGZIP(), []int{0}
}

func (x *Light) GetPowered() bool {
	if x != nil {
		return x.Powered
	}
	return false
}

func (x *Light) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_RGB
}

func (x *Light) GetColor() uint32 {
	if x != nil {
		return x.Color
	}
	return 0
}

var File_lighting_proto protoreflect.FileDescriptor

var file_lighting_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x52, 0x0a, 0x05, 0x4c, 0x69, 0x67, 0x68, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x6f, 0x77,
	0x65, 0x72, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x70, 0x6f, 0x77, 0x65,
	0x72, 0x65, 0x64, 0x12, 0x19, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x05, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63,
	0x6f, 0x6c, 0x6f, 0x72, 0x2a, 0x19, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x07, 0x0a, 0x03,
	0x52, 0x47, 0x42, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x52, 0x47, 0x42, 0x57, 0x10, 0x01, 0x32,
	0x46, 0x0a, 0x08, 0x4c, 0x69, 0x67, 0x68, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x1c, 0x0a, 0x08, 0x53,
	0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x06, 0x2e, 0x4c, 0x69, 0x67, 0x68, 0x74, 0x1a,
	0x06, 0x2e, 0x4c, 0x69, 0x67, 0x68, 0x74, 0x22, 0x00, 0x12, 0x1c, 0x0a, 0x08, 0x47, 0x65, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x06, 0x2e, 0x4c, 0x69, 0x67, 0x68, 0x74, 0x1a, 0x06, 0x2e,
	0x4c, 0x69, 0x67, 0x68, 0x74, 0x22, 0x00, 0x42, 0x1b, 0x5a, 0x19, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x65, 0x68, 0x61, 0x61, 0x73, 0x73, 0x2f, 0x63, 0x6d,
	0x64, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lighting_proto_rawDescOnce sync.Once
	file_lighting_proto_rawDescData = file_lighting_proto_rawDesc
)

func file_lighting_proto_rawDescGZIP() []byte {
	file_lighting_proto_rawDescOnce.Do(func() {
		file_lighting_proto_rawDescData = protoimpl.X.CompressGZIP(file_lighting_proto_rawDescData)
	})
	return file_lighting_proto_rawDescData
}

var file_lighting_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_lighting_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_lighting_proto_goTypes = []interface{}{
	(Type)(0),     // 0: Type
	(*Light)(nil), // 1: Light
}
var file_lighting_proto_depIdxs = []int32{
	0, // 0: Light.type:type_name -> Type
	1, // 1: Lighting.SetState:input_type -> Light
	1, // 2: Lighting.GetState:input_type -> Light
	1, // 3: Lighting.SetState:output_type -> Light
	1, // 4: Lighting.GetState:output_type -> Light
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_lighting_proto_init() }
func file_lighting_proto_init() {
	if File_lighting_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lighting_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Light); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lighting_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lighting_proto_goTypes,
		DependencyIndexes: file_lighting_proto_depIdxs,
		EnumInfos:         file_lighting_proto_enumTypes,
		MessageInfos:      file_lighting_proto_msgTypes,
	}.Build()
	File_lighting_proto = out.File
	file_lighting_proto_rawDesc = nil
	file_lighting_proto_goTypes = nil
	file_lighting_proto_depIdxs = nil
}
