/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.1
// 	protoc              v3.20.1
// source: lighting.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as lighting_pb from './lighting_pb';


export class LightingClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorSetState = new grpcWeb.MethodDescriptor(
    '/Lighting/SetState',
    grpcWeb.MethodType.UNARY,
    lighting_pb.Light,
    lighting_pb.Light,
    (request: lighting_pb.Light) => {
      return request.serializeBinary();
    },
    lighting_pb.Light.deserializeBinary
  );

  setState(
    request: lighting_pb.Light,
    metadata: grpcWeb.Metadata | null): Promise<lighting_pb.Light>;

  setState(
    request: lighting_pb.Light,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: lighting_pb.Light) => void): grpcWeb.ClientReadableStream<lighting_pb.Light>;

  setState(
    request: lighting_pb.Light,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: lighting_pb.Light) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/Lighting/SetState',
        request,
        metadata || {},
        this.methodDescriptorSetState,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/Lighting/SetState',
    request,
    metadata || {},
    this.methodDescriptorSetState);
  }

  methodDescriptorGetState = new grpcWeb.MethodDescriptor(
    '/Lighting/GetState',
    grpcWeb.MethodType.UNARY,
    lighting_pb.Light,
    lighting_pb.Light,
    (request: lighting_pb.Light) => {
      return request.serializeBinary();
    },
    lighting_pb.Light.deserializeBinary
  );

  getState(
    request: lighting_pb.Light,
    metadata: grpcWeb.Metadata | null): Promise<lighting_pb.Light>;

  getState(
    request: lighting_pb.Light,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: lighting_pb.Light) => void): grpcWeb.ClientReadableStream<lighting_pb.Light>;

  getState(
    request: lighting_pb.Light,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: lighting_pb.Light) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/Lighting/GetState',
        request,
        metadata || {},
        this.methodDescriptorGetState,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/Lighting/GetState',
    request,
    metadata || {},
    this.methodDescriptorGetState);
  }

}

